# Generated by Django 4.1.5 on 2023-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_medicine', models.CharField(max_length=10)),
                ('dosage', models.CharField(max_length=10)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Medicine',
            },
        ),
    ]
