# Generated by Django 4.1.5 on 2023-01-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddosage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['-tracked_medicine'], 'verbose_name': 'Medicine'},
        ),
    ]
