# Generated by Django 4.1.5 on 2023-01-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_age_userprofile_sex'),
        ('meddosage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
