# Generated by Django 4.1.5 on 2023-01-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddosage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
