# Generated by Django 5.0.1 on 2024-02-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddosage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='user',
            new_name='owner',
        ),
    ]
