# Generated by Django 5.0.1 on 2024-02-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddosage', '0002_rename_user_medicine_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='owner',
            new_name='user',
        ),
    ]
