# Generated by Django 4.1.5 on 2023-01-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_alter_userprofile_country_and_more'),
        ('meddosage', '0002_alter_medicine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='tracked_medicine',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
