# Generated by Django 4.1.5 on 2023-01-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddosage', '0004_remove_medicine_profile_alter_medicine_dosage_and_more'),
        ('accounts', '0002_alter_userprofile_options_alter_userprofile_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
