# Generated by Django 4.1.5 on 2023-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_avatar_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='media/profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
